---
title: Bases de Datos Ecuatorianas
subtitle: Laboratorio de Investigación para el Desarrollo del Ecuador
author: Daniel Sánchez-Pazmiño
date: 2024-07-31
format: 
    revealjs:
        theme: serif
date-format: "long"
lang: es
bibliography: ../../references/ecu_papers.bib
---

# Introducción {.smaller}

- ¿Por qué preocuparse por entender datos del Ecuador?

- ¿Qué tienen en común algunos de los mejores artículos de investigadores ecuatorianos o que se enfocan en Ecuador?

    - @adao_etal22: *The key input fed into our empirical analysis is a unique administrative data set from Ecuador that merges firm-to-firm transaction data, employer-employee matched data, owner-firm matched data, and firm-level customs transaction records.*

    - @bosch_schady19: *To analyze the effects of transfers on the choice between formal and informal employment, we used the cédula of focal women, as reported in the 2007/08 poverty census, and merged in data on contributions to social security from IESS*. 

    - @rivadeneira23: *[...] I use hand-collected and digitized historical tax records from Ecuador’s Spanish colonial regime to estimate the long-run effects of a forced labor institution named concertaje.*

# ¿Es suficiente una buena idea? {.smaller}

- Una buena pregunta de investigación es fundamental, pero no suficiente.

- Es generalmente necesario contar con una demostración empírica que respalde nuestra respuesta a la pregunta de investigación
    - Esto implica contar con información o **datos**.

- Un acceso factible a datos que permitan responder la pregunta define el éxito del proyecto.
    - ¿Qué datos son necesarios?
    - ¿Dónde están datos? ¿Cómo se pueden obtener?
    - ¿Son fácilmente accesibles? ¿Cuanto tiempo/recursos se necesita para obtenerlos?

# Recolección de datos {.smaller}

- Recolección primaria de datos: recolección directa del fenómeno de interés por el investigador
    - Surge de las fuentes primarias (i.e. el encuestado)
    - Puede ser costoso y requerir tiempo.
    - Encuestas, experimentos, observaciones.
    - Se requerirá una junta de revisión ética (*internal review board*).

- Fuentes secundarias: información recolectada por otros investigadores o instituciones, utilizable para nuestros propósitos.
    - Gratuitos o pagados.
    - Censos, datos de encuesta, registros administrativos, datos de redes sociales.

- **Este curso se enfoca en el uso de fuentes secundarias**.

# Problemas comunes en investigaciones del Ecuador {.smaller}

- Existen fuentes secundarias de datos, pero no siempre son fáciles de encontrar o acceder.

- La capacidad estadística del Ecuador ha ido decreciendo en los últimos años.

- La información puede ser limitada o no disponible en formatos/agregaciones útiles.

- Se puede requerir de permisos especiales.

- La documentación de los datos puede ser limitada y la calidad de los datos no se garantiza.

- La educación formal en el uso de datos ecuatorianos de investigación es limitada.

# Tipos de datos {.smaller}

1. **Censos**: recolección de información de toda una población o una muestra considerable de la misma. 
    - Ejemplo: Censo de Población y Vivienda, Censo de Empresas.
    - Ventajas: excelente cobertura, gran cantidad de variables de interés. 
    - Desventajas: poco frecuentes, no disponibles para varias situaciones y/o agregaciones.

2. **Encuestas**: recolección de información de una muestra de la población.
    - Ejemplo: Encuesta Nacional de Empleo, Desempleo y Subempleo (ENEMDU), Encuesta Nacional de Salud y Nutrición (ENSANUT).
    - Ventajas: dependiendo del caso, actualización frecuente y gran cantidad de variables de interés, posibilidad de obtener información detallada.
    - Desventajas: limitaciones en la cobertura, calidad de la información, generalmente no es posible realizar seguimiento de individuos.

# Tipos de datos {.smaller}

3. **Datos administrativos**: recolectados por instituciones generalmente públicas para propósitos no investigativos, pero que pueden ser utilizados de todas formas.
    - Ejemplo: registros de empleo del IESS, registros de empresas de la Superintendencia de Compañías.
    - Ventajas: gran cobertura, actualización frecuente, posibilidad de seguimiento a unidades individuales.
    - Desventajas: limitaciones en la calidad, formatos o acceso inconvenientes, complicaciones estadísticas, falta de variables de interés investigativo.

# Varias presentaciones de datos {.smaller}

- Es muy importante saber diferenciar las maneras en las que la información se presenta y cómo podemos acceder a la misma. 

- Para esto, es importante reconocer la *unidad de observación* de los datos.
    - ¿De qué se está recolectando información?

- Ejemplo: Encuesta Nacional de Empleo, Desempleo y Subempleo (ENEMDU).
    - Unidad de observación: individuos (personas) y hogares.

# Tipos de presentación de datos {.smaller}

- Existen diferentes formas en las que una institución libera datos:
    - Metadatos: información **sobre** los datos, como variables, códigos, definiciones, etc.
    - Microdatos o datos individuales: información a nivel de individuos, empresas, hogares, etc.
    - Agregados o tabulados: información resumida, generalmente a nivel de grupos como provincias, sectores económicos, etc.
    - Reportes: información presentada en documentos, generalmente con análisis y gráficos. También incluye tableros o *dashboards* dinámicos.
    - Base de datos: varias tablas de microdatos que pueden ser unidas por un identificador

# Panorama general de los datos ecuatorianos {.smaller}

- Existen varias instituciones que producen datos en Ecuador:
    - Instituciones públicas (gobiernos central y locales)
    - Iniciativas no gubernamentales (sociedad civil)
    - Organizaciones internacionales

- Una mayoría de los datos fácilmente utilizables provienen del **Instituto Nacional de Estadística y Censos (INEC)**.
    - Todo país tiene un instituto con un mandato de recolección de datos estadísticos.
    - Encargado de la administración de censos y encuestas
    - Mantiene una biblioteca de información para datos de otras instituciones 

# Panorama general de los datos ecuatorianos {.smaller}

- La información macroeconómica proviene del **Banco Central del Ecuador (BCE)**

- Otras instituciones importantes a considerar:
     - Registro Civil: información demográfica
     - Servicio de Rentas Internas (SRI): información tributaria
     - Superintendencia de Compañías: información de empresas y bolsa de valores
     - Instituto Ecuatoriano de Seguridad Social (IESS): empleo, salud, pensiones

# Utilizando el sitio web del INEC {.smaller}

- El sitio web https://www.ecuadorencifras.gob.ec/ es la principal fuente de datos del INEC.
    - Se accede a datos seleccionando la opción *Estadísticas*

[INEC](../img/inec_sitio_web_1.png)

# Referencias

:::{.references}

:::