---
title: "Ecuadorian Datasets"
subtitle: "A brief review of the Ecuadorian research data landscape"
author: "Laboratorio de Investigación para el Desarrollo del Ecuador"
format: pdf
number-sections: true
---

**Instructor**: Daniel Sánchez, MA

**Module length**: 3 hours

**Course level**: Introductory

**Prerequisite knowledge**: None

**GitHub repository**: https://github.com/laboratoriolide/ecuadorian-datasets

# Course overview

This short module provides an overview of the existing data for Ecuador, with a focus on datasets which can be leveraged for quantitative social science research. Oftentimes, young researchers may hit a hard stop in their research due to their inability to find good data to answer their research questions. This module aims to provide students with the tools to find and access existing datasets, as well as to understand the methodological issues that come with using them. I introduce the existing dataset types, where to find them, the institutions that produce them, how to access them, methodological issues, and the potential for future research. The module is designed for students who are interested in conducting research in Ecuador, but are not familiar with the existing data landscape.

# Module contents {#sec-contents}

The following is a planned outline of the course. This may change depending on the pace of the class. The module's materials, including slides, links, datasets and all other files (if applicable), will be released in the course's [GitHub repository](https://github.com/laboratoriolide/ecuadorian-datasets).

## Lecture 1: Introduction and basic datasets

- Introduction to the module: objectives and expectations
- Types of datasets: administrative, surveys, and experimental
- Overview of the Ecuadorian data landscape
    - Public institutions (central and local governments)
    - Non-governmental initiatives (academic and civil society)
    - International organizations

- Main public institutions producing datasets
    - Instituto Nacional de Estadística y Censos (INEC)
    - Banco Central del Ecuador (BCE)
    - Registro Civil
    - Servicio de Rentas Internas (SRI)
    - Instituto Ecuatoriano de Seguridad Social (IESS)

<!-- 

For each dataset, we'll cover the following aspects:
 - What is the dataset about?
 - What can you do with it?
 - How to access it?
 - Where to find documentation?
 - Problems and limitations
 - Examples of research using the dataset

!--->

- Main survey datasets for researchers
    - Employment surveys - Encuesta Nacional de Empleo, Desempleo y Subempleo (ENEMDU)
    - Population Census - Censo de Población y Vivienda 
    - Health surveys - Encuesta Nacional de Salud y Nutrición (ENSANUT)

- Main administrative datasets for researchers
    - Employment and salary data - Registro Estadístico de Empleo en la Seguridad Social (REESS)
    - Business data - Directorio de Compañías (Superintendencia de Compañías) and Directorio de Empresas y Establecimientos (INEC)
    - Tax data: sales, purchases, value added tax, closures and suspensions (SRI).
    - Demographic and morbidity data - Registro Civil
    - Social security data - Instituto Ecuatoriano de Seguridad Social (IESS)

- Useful aggregator websites
    - Banco de Datos Abiertos Ecuador (Central Government)
    - Banco de Datos Abiertos INEC
    - Archivo Nacional de Metadatos Estadísticos (INEC)
    - Geoportal INEC

## Lecture 2: Beyond the basics

- Local Government dataset initiatives
- *Open Government* initiatives
    - Gobierno Abierto (Local Governments)
    - Banco de Datos Abiertos Ecuador (Central Government)
- International country level datasets
    - World Bank
    - Inter-American Development Bank
    - United Nations
    - CEPAL
- International Surveys
    - AmericasBarometer
    - Latinobarómetro
    - World Values Survey
- International and non-governmental initiatives:
    - Datalat
    - Observatorio Legislativo
    - Observatorio de Contratación Pública (Fundación Ciudadanía y Desarrollo)

- Methodological challenges in using Ecuadorian datasets
    - Metadata and documentation
    - Ease of access and availability
    - Data quality, reliability and ethical considerations
    - Accessing government institutions outside Ecuador
    - Comparison to other Latin American countries
    - Data cleaning and processing, common issues
    - Reproducibility in peer-reviewed research
    - How do published authors use Ecuadorian datasets?

# Evaluation

This short module will be graded following the program's grading policy. Please consult the regulation handbook for more information. Attendance is mandatory, and students are encouraged to participate in the two lectures. All communications should be made through Slack. 

# Communication

All communications to the instructor should be made through the course's Slack channel. I do not monitor email regularly, so please use Slack for all communications if you need a timely response.
