---
title: "Bases de Datos Ecuatorianas"
subtitle: "Una breve revisión del panorama ecuatoriano de datos de investigación"
author: "Laboratorio de Investigación para el Desarrollo del Ecuador"
format: pdf
number-sections: true
---

# Descripción del curso

Este módulo proporciona una visión general de los datos existentes para Ecuador, con un enfoque en conjuntos de datos que pueden ser aprovechados para la investigación en ciencias sociales cuantitativas. A menudo, un investigador puede encontrar obstáculos encontrando datos que respondan a sus preguntas de investigación. Este módulo tiene como objetivo proporcionar las herramientas para encontrar y acceder a conjuntos de datos existentes, así como entender los problemas metodológicos que implican su uso. Se introducen los tipos de conjuntos de datos existentes, dónde encontrarlos, las instituciones que los producen, cómo acceder a ellos, los problemas metodológicos y el potencial para investigaciones futuras. El módulo está diseñado para quiénes estén interesados en realizar investigaciones enfocadas en el Ecuador, pero que no están familiarizados con el panorama de datos existente. **No** se contempla la recolección de datos mediante experimentos o encuestas, sino el uso de datos recolectados por otras personas o instituciones.

# Contenidos {#sec-contents}

El siguiente es un esquema planificado del curso. Esto puede cambiar dependiendo del ritmo de la clase. Los materiales del módulo, incluidos las diapositivas, enlaces, conjuntos de datos (si es que aplica) y todos los demás archivos, se publicarán en el Google Drive del programa.

## Clase 1: Introducción y conjuntos de datos básicos

- Introducción al módulo
- Tipos de conjuntos de datos y como se presentan ante el usuario

- Panorama general de los datos ecuatorianos
    - Instituciones públicas (gobiernos central y locales)
    - Iniciativas no gubernamentales (académicas y de la sociedad civil)
    - Organizaciones internacionales

- Principales instituciones públicas que producen conjuntos de datos
    - Instituto Nacional de Estadística y Censos (INEC)
    - Banco Central del Ecuador (BCE)
    - Registro Civil
    - Servicio de Rentas Internas (SRI)
    - Instituto Ecuatoriano de Seguridad Social (IESS)

<!-- 

Para cada conjunto de datos, cubriremos los siguientes aspectos:
 - ¿De qué trata el conjunto de datos?
 - ¿Qué se puede hacer con él?
 - ¿Cómo acceder a él?
 - ¿Dónde encontrar la documentación?
 - Problemas y limitaciones
 - Ejemplos de investigaciones utilizando el conjunto de datos

!--->

- Principales conjuntos de datos de encuestas para investigadores
    - Encuestas de empleo - Encuesta Nacional de Empleo, Desempleo y Subempleo (ENEMDU)
    - Censo de Población y Vivienda
    - Encuestas de salud - Encuesta Nacional de Salud y Nutrición (ENSANUT)
    - Otros

- Revisión a fondo: Encuesta Nacional de Empleo, Desempleo y Subempleo (ENEMDU)
    - ¿De qué trata el conjunto de datos?
    - ¿Qué se puede hacer con él?
    - ¿Cómo acceder a él?
    - ¿Dónde encontrar la documentación?

- Principales conjuntos de datos administrativos para investigadores
    - Datos de empleo y salarios - Registro Estadístico de Empleo en la Seguridad Social (REESS)
    - Datos empresariales - Directorio de Compañías (Superintendencia de Compañías) y Directorio de Empresas y Establecimientos (INEC)
    - Datos tributarios: ventas, compras, impuesto al valor agregado, cierres y suspensiones (SRI)
    - Voto y elecciones - Registro Electoral (Consejo Nacional Electoral)

- Sitios web agregadores útiles
    - Banco de Datos Abiertos Ecuador (Gobierno Central)
    - Banco de Datos Abiertos INEC
    - Archivo Nacional de Metadatos Estadísticos (INEC)

## Clase 2: Más allá de lo básico

- Iniciativas de *Gobierno Abierto*
    - Gobierno Abierto Quito, Quito Cómo Vamos.
    - Banco de Datos Abiertos Ecuador (Gobierno Central)

- Conjuntos de datos internacionales a nivel de país
    - Banco Mundial (WDI, WGI)
    - Banco Interamericano de Desarrollo
    - Naciones Unidas
    - CEPAL

- Encuestas internacionales
    - Barómetro de las Américas
    - Latinobarómetro
    - Encuesta Mundial de Valores
- Iniciativas internacionales y no gubernamentales:
    - Datalat
    - Observatorio Legislativo
    - Observatorio de Contratación Pública (Fundación Ciudadanía y Desarrollo)
    - Asobanca

- Datos especiales
    - Geoportal INEC
    - Datos macroeconómicos: BCE, CEPAL, FMI, Banco Mundial, Cordes (NowCast).

- Desafíos metodológicos en el uso de conjuntos de datos ecuatorianos
    - Metadatos y documentación
    - Facilidad de acceso y disponibilidad
    - Calidad de los datos, fiabilidad y consideraciones éticas
    - Acceso a instituciones gubernamentales fuera de Ecuador
    - Comparación con otros países de América Latina
    - Limpieza y procesamiento de datos, problemas comunes
    - Reproducibilidad en la investigación revisada por pares
    - ¿Cómo utilizan los autores publicados los conjuntos de datos ecuatorianos?

# Metodología

Las primeras dos clases se conducirán de forma sincrónica, con demostraciones del instructor y discusiones en grupo. La participación activa en la discusión y planteamiento de preguntas es recomendada para sacar provecho a este módulo. En la tercera clase de ayudantía, se planificarán sesiones personalizadas en donde los docentes pueden acudir al instructor con preguntas específicas sobre sus proyectos de investigación o una base de datos que le interese, y recibir asesoramiento sobre cómo encontrar, entender y acceder a los datos necesarios. De igual forma, es posible trabajar en temas más avanzados como el análisis de datos, la limpieza y la visualización, o la citación de datos en trabajos académicos. En caso de que el tiempo de las primeras dos clases no sea suficiente para cubrir todos los temas, se podrá utilizar la tercera clase para completar el contenido.